services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - lanes-network
    ports:
      - 5432:${DATABASE_PORT}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DATABASE_PANEL_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DATABASE_PANEL_PASSWORD}
    ports:
      - 8080:${DATABASE_PANEL_PORT}
    depends_on:
      - db

networks:
  lanes-network:
    driver: bridge

volumes:
  postgres-data:
